openapi: 3.0.3
info:
  title: NetBox REST authentication-check API
  version: 4.6.5 (4.6)
  license:
    name: Apache v2 License
servers:
- url: ''
  description: NetBox
tags:
- name: authentication-check
paths:
  /api/authentication-check/:
    get:
      operationId: authentication_check_retrieve
      description: Return the user making the request, if authenticated successfully.
      parameters:
      - in: query
        name: brief
        schema:
          type: boolean
        description: Return only brief fields for each object.
      - in: query
        name: fields
        schema:
          type: string
        description: 'Comma-separated list of fields to include in the response. Example: `fields=id,name`.'
      - in: query
        name: omit
        schema:
          type: string
        description: 'Comma-separated list of fields to exclude from the response. Example: `omit=description,tags`.'
      tags:
      - authentication-check
      security:
      - cookieAuth: []
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: '`Token <token>` (v1) or `Bearer <key>.<token>` (v2)'
